schema_version = "1.0.0"

id = "planetopbr"
name = "Plane to PBR"
version = "0.1.0"
tagline = "Add>Mesh>Import an image as a PBR-textured plane"
type = "add-on"

maintainer = "Amelia Scarlett"
license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

[permissions]
files = "Read texture files from disk"
